### ISSUE TITLE
Duplicate keys 'radon.artifacts.Ansible'

### ISSUE THREAD

**Issue by chinmaya-dehury** [radon-h2020/radon-particles#28]
Checked to orchestrate ‘[sockshp](url)’ service blueprint with xopera. This seems to be working.

However while trying out to export and deploy the service from the unzipped CSAR. 
However while trying out  '[EC2_on_AWS](https://github.com/radon-h2020/radon-particles/tree/master/servicetemplates/radon.blueprints.examples/EC2_on_AWS)' and  '[ToyExampleNifi](https://github.com/radon-h2020/radon-particles/tree/master/servicetemplates/radon.blueprints.datapipeline/ToyExampleNifi)' service blueprints, I got following errors:

`_definitions/radonartifacts__Ansible.tosca:4:3: [MapWrapper] Duplicate keys 'radon.artifacts.Ansible' found in _definitions/radonartifacts__Ansible.tosca:4:3 and _definitions/radonartifacts__Ansible.tosca:4:3`

The content of one of the file `radonartifacts__Ansible.tosca` is as follows: 

```
tosca_definitions_version: tosca_simple_yaml_1_3

artifact_types:
  radon.artifacts.Ansible:
    derived_from: tosca.artifacts.Implementation
    metadata:
      abstract: "false"
      final: "false"
      targetNamespace: "radon.artifacts"
    file_ext: [ yml, yaml ]

```

Would you suggest some hints to fix this issue?

-Thanks
